version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-deploy-api:latest
    container_name: nginx-deploy-api
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /etc/nginx:/etc/nginx
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=false
    networks:
      - nginx-network
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  nginx-network:
    driver: bridge

volumes:
  mysql_data: 