version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx:/etc/nginx
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_NAME=nginx_deploy
    depends_on:
      - db
    privileged: true  # 需要特权模式来管理系统服务

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=nginx_deploy
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 